### ISSUE TITLE
Visual Studio Version

### ISSUE THREAD

**Issue by pavlalexandr** [nopSolutions/nopCommerce-plugin-template-VS#1]
It would be great if you point which version of Visual Studio this template for.

**Comment by rhyous** [comment]
I tried in VS 2017 and VS 2019 and the template doesn't show up. I couldn't find an Online template for VS 2019, but found one for VS 2017, but when I tried to use it, nothing happened, it doesn't create a project.

**Comment by skoshelev** [comment]
Hi @rhyous. Template work good on the both visual studio 2017 and 2019

**Comment by skoshelev** [comment]
Closed #1
