### ISSUE TITLE
Errore MSB3202:  ClearPluginAssemblies.proj  not found...

### ISSUE THREAD

**Issue by luc-cap** [nopSolutions/nopCommerce-plugin-template-VS#10]
Hi,
     there is a mistake in Nop.Plugin.csproj  file.

replace this row:
   `<ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\Build\ClearPluginAssemblies.proj" />`
   

with this:
   `<ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />`

**Comment by skoshelev** [comment]
Closed #10
