### ISSUE TITLE
https://docs.nopcommerce.com/en/developer/plugins/how-to-write-plugin-4.50.html

### ISSUE THREAD

**Issue by ekjuanrejon** [nopSolutions/nopCommerce-plugin-template-VS#14]
template seems to be different than the documentation

**Comment by skoshelev** [comment]
Hi @ekjuanrejon.
Please clarify what do you mean? This is a general template for creating a plugin, it was not intended as an illustration for documentation. The purpose of this template is to simplify the initial setup for a new plugin.
