### ISSUE TITLE
`IDependencyRegistrar` is not used anymore

### ISSUE THREAD

**Issue by Anton-A-Sakovich** [nopSolutions/nopCommerce-plugin-template-VS#15]
I've noticed that the template for version 4.60 of nopCommerce contains `DependencyRegistrar` class in `Areas/Admin/Infrastructure` ([link](https://github.com/nopSolutions/nopCommerce-plugin-template-VS/blob/19e2368ae97900e5c8d7e615a6675784fa9d88a4/Nop.Plugin%20Template%204.60/Areas/Admin/Infrastructure/DependencyRegistrar.cs)). It seems to me that this class should be removed from the template because `IDependencyRegistrar` was removed in [5060165a](https://github.com/nopSolutions/nopCommerce/commit/5060165afa6e927ef59f3258281ba5f5b0eaf81e).

**Comment by skoshelev** [comment]
Hi @Anton-A-Sakovich, Indeed, the file was in the package, but it was not copied when creating the plugin; in version 4.70 I deleted the file completely. Thank you for your help.

Closed #15
