### ISSUE TITLE
Installing this Template

### ISSUE THREAD

**Issue by zerokewl88** [nopSolutions/nopCommerce-plugin-template-VS#2]
Hi, 

I am trying to install the template, but VS 2019, is unable to find it.

I have taken the following steps to install this..

**OK** - Download template folder
**OK** - Copy downloaded folder or zip archive into the one of this folders:
**I copied the "Nop.Plugin Template 4.20" folder, into ->** C:\Users\{Username}\Documents{VisualStudio}\Templates\ProjectTemplates

During this time, i have VS closed, i then also clean the template directories here "C:\Users\{username}\Documents\Visual Studio 2019\Templates\ProjectTemplates" and then start visual studio.

Typing in nop, plugin, or searching through C# project templates, i can't seem to find the template?

I then tried to load just the csproj, itself, and then export it, but that also fails. Loading the csproj, the project already has missing folders. 

![image](https://user-images.githubusercontent.com/5489947/69105094-e5838880-0a9c-11ea-882d-e46be6388112.png)

Is there anything that i'm not doing to get this to work, could you please suggest anything i can try to use this template please.

![image](https://user-images.githubusercontent.com/5489947/69105410-be798680-0a9d-11ea-9d4a-6bea4b43f558.png)

Thank you.

**Comment by xxl-cc** [comment]
i have same problem

**Comment by ruinpsilva** [comment]
Same problem here! I also tried to load the template into Rider without success.

**Comment by rockybalog** [comment]
I have the same problem

**Comment by davidnard** [comment]
Template for version 4.10 with Visual Studio 2017 is loading without issue as of 12/12/19. You could try installing vs'17 community edition to see if it works for you. If it does, it may be a compatibility issue with vs'19

**Comment by rockybalog** [comment]
> Template for version 4.10 with Visual Studio 2017 is loading without issue as of 12/12/19. You could try installing vs'17 community edition to see if it works for you. If it does, it may be a compatibility issue with vs'19

I need to use it 2019! I do think it is a compatibility issue. Is nopSolutions going to fix it?

MS fixed it! There was an update to VS Community 2019 16.4.1 and now the template shows up in th elist!

**Comment by zerokewl88** [comment]
Can we not just use VS Community '17, to open it, save the project, then reopen it in VS 19 ?

**Comment by zzDave** [comment]
This is a visual studio 2019  bug.   It is appearing in the list, but the search does not work.   If you scroll down, you will find it.

https://developercommunity.visualstudio.com/content/problem/802036/custom-project-template-ignored.html

**Comment by kristjantoots** [comment]
This has been now fixed (inc. search) and works with Visual Studio 2019 16.4.4

**Comment by skoshelev** [comment]
Closed #2
