### ISSUE TITLE
$safeprojectname$ Template Parameter Not Working

### ISSUE THREAD

**Issue by richardohara** [nopSolutions/nopCommerce-plugin-template-VS#3]
I am getting compiler errors related to the $safeprojectname$ template parameter. Is there something in the .vstemplate file that needs to change? The only thing I see is that TargetFileName and File are no longer valid and I have changed them to match the name of my .csproj file. Is there any other change I need to make to any of the default values?

**Comment by skoshelev** [comment]
f you create a plugin using a template then the $ safeprojectname $ parameter works well. If you just connected the Nop.Plugin.csproj file to your project, then you will have to change all namespaces, since they are tied to the substitution of the $ safeprojectname $ parameter.

Closed #3
