### ISSUE TITLE
Adjust the OutputPath and remove the "nop.plugin" part.

### ISSUE THREAD

**Issue by mozahr** [nopSolutions/nopCommerce-plugin-template-VS#4]
For some reason the output path was causing problem for the plugin not to show in the list of local plugins in the admin section: 	  <OutputPath>..\..\Presentation\Nop.Web\Plugins\$safeprojectname$</OutputPath>
$safeprojectname$ was replaced with Nop.Plugin.Misc.NameIChoose .. and the 'Nop.Plugin.' part should be removed.

**Comment by skoshelev** [comment]
Hi @mozahr. We decided not to remove anything from the plugin name, as the plugin naming format is only recommended but not required.

Closed #4
