### ISSUE TITLE
Inheritance from IPlugin

### ISSUE THREAD

**Issue by Marjani** [nopSolutions/nopCommerce-plugin-template-VS#6]
According to [document](https://docs.nopcommerce.com/en/developer/plugins/how-to-write-plugin-4.30.html)  required to implements IPlugin interface, but there isn't any Plugin Name class that  implements IPlugin and on startup project PluginType set null [here](https://github.com/nopSolutions/nopCommerce/blob/0029c9b7a830b0904554fe6687c5bba287fc7c77/src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationPartManagerExtensions.cs#L545)

This prevents the plugin from being installed and stays in the PluginNamesToInstall list

**Comment by raminfosystems** [comment]
Pull request created and should be able to generate a default file from the template.

**Comment by skoshelev** [comment]
Fixed by https://github.com/nopSolutions/nopCommerce-plugin-template-VS/pull/7
